* Inspector Dashboard
***  Script ID files are not exposed in this repo for security purposes.
*** Building (look at Makefile)
- The build architecture here is some what unique--Makefile is used to checkout the production branch into a git worktree before building and bundling into a webpack.
- The project can also be build locally, so long as one has a mechanism of serving the build directory. I simply used in-build python3 http module.
  #+BEGIN_SRC console
  $ make local
  $ cd ./dist
  $ python3 -m "http.server" 9001
  #+END_SRC
** TODO
- [X] Implement build pipeline via Makefile which compiles TypeScript and bundles webpack.
- [X] Implement deployment pipeline to serve webpack from GH pages.
- [X] Establish very simple OpenLayer API bundle in main application.
- [ ] Determine some type of sane type system for sheet data.
- [ ] Homebrewed ORM/interface to sheets, ideally no exposure of keys should occur.
- [ ] Read in data rows from sheets.
- [ ] Implement geocoding via address from pulled data: possible api is nominatim.
- [ ] Implement statistical modal/interface for data.
- [ ] Bundle some charting library for data visualization.
