* Inspector Dashboard
** Deployment
** Deploy a published project
You can deploy script projects as web apps, add-ons, or executables. You can create deployments in the script editor, in the project manifest, or using clasp.

To deploy a project with clasp, first create an immutable version of the Apps Script project. A version is a "snapshot" of a script project and is similar to a read-only branched release.
#+BEGIN_SRC console
$ clasp version [description]
#+END_SRC

This command displays the newly created version number. Using that number, you can deploy and undeploy instances of your project:
#+BEGIN_SRC console
$ clasp deploy [version] [description]
$ clasp undeploy <deploymentId>
#+END_SRC

This command updates an existing deployment with a new version and description:
#+BEGIN_SRC console
$ clasp redeploy <deploymentId> <version> <description>
#+END_SRC

** List deployments
This command lists the script project's deployment IDs, versions, and their descriptions.
#+BEGIN_SRC console
$ clasp deployments
#+END_SRC

** Open the project in the Apps Script editor
This command opens a script project in the Apps Script editor. The editor is launched as a new tab in your default web browser.
#+BEGIN_SRC console
$ clasp open
#+END_SRC

** Notes
***  Script ID files are not exposed in this repo for security purposes.
